# Generated by Django 2.1.15 on 2025-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooksmodel',
            name='summary',
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='publisher',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='image',
            field=models.ImageField(upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
