# Generated by Django 2.1.15 on 2025-12-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooksmodel',
            name='borrow_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
