# Generated by Django 2.1.15 on 2025-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0002_auto_20251114_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
