# Generated by Django 2.1.15 on 2025-11-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0004_auto_20251115_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooksmodel',
            name='book_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
