# Generated by Django 2.1.15 on 2025-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0006_borrowrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooksmodel',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
