# Generated by Django 2.1.15 on 2025-11-16 16:44

from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0007_ebooksmodel_is_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
    ]
