# Generated by Django 2.1.15 on 2025-11-16 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0008_borrowrecord_borrowed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrowed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
