# Generated by Django 2.1.15 on 2025-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0009_auto_20251116_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrowed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
