# Generated by Django 2.1.15 on 2025-11-16 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0012_auto_20251116_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 16, 16, 53, 16, 249078, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
